model:
  arch: minigpt4
  model_type: pretrain_vicuna0

  max_txt_len: 1024
  end_sym: "###"
  prompt_path: "prompts/alignment.txt"
  prompt_template: '###Human: {} ###Assistant: '
  ckpt: '/home/t-jiaweiwang/Project/LLM-Safty/Visual-Adversarial-Examples-Jailbreak-Large-Language-Models/ckpts/pretrained_minigpt4.pth'
  lora_r: 0
  lora_r_backbone: 16
  freeze_linear: True
  freeze_vit: True

datasets:
  robustvlguard_general: 
    batch_size: 2
    vis_processor:
      train:
        name: "robustvlguard_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

  robustvlguard_safety_llm:
    batch_size: 2
    vis_processor:
      train:
        name: "robustvlguard_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

  robustvlguard_vlguard:
    batch_size: 2
    vis_processor:
      train:
        name: "robustvlguard_image_train"
        image_size: 224
    text_processor:
      train:
        name: "blip_caption"

run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 4
  # iters_per_epoch: 200
  num_workers: 4
  warmup_steps: 200

  seed: 42
  output_dir: "output/minigpt4_stage3_robustvlguard_finetune_backbone_lr1e-5"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True
  job_name: minigpt4_finetune